### ISSUE TITLE
Cannot use in Rails 5

### ISSUE THREAD

**Issue by goalkeeper112** [Rodrigora/devise-verifiable#1]
Hi Rodrigora, when i try install this gem in my rails 5 app, show me this error:

Bundler could not find compatible versions for gem "devise":
  In snapshot (Gemfile.lock):
    devise (= 4.2.0)

  In Gemfile:
    devise

```
devise-verifiable was resolved to 0.0.1, which depends on
  devise (~> 3.5)
```

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

This my Gemfile:

source 'https://rubygems.org'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'

gem 'rails', '5.0.0'
# Use sqlite3 as the database for Active Record
# gem 'sqlite3'
# Use SCSS for stylesheets

gem "compass-rails"
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets

gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views

gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

gem 'rest-client'
gem 'rollbar'
# Use jquery as the JavaScript library

gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks

gem 'turbolinks'
gem 'capistrano3-nginx', '~> 2.0'
gem 'record_tag_helper', '~> 1.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder

gem 'jbuilder', '~> 2.5'
# bundle exec rake doc:rails generates the API under doc/api.

gem 'sdoc', '~> 0.4.0', group: :doc
# Images upload and proccessing

gem 'carrierwave'
gem 'mini_magick'
gem 'gon'
gem 'jquery-turbolinks'
gem "fog-aws"
gem 'kaminari'
gem 'groupdate'
gem "chartkick"
gem 'hightop'
# gem "refile", require: "refile/rails"
# gem "refile-mini_magick"
# Semantic UI stylesheets css

gem 'semantic-ui-sass', github: 'doabit/semantic-ui-sass'
gem 'nokogiri'
gem 'premailer-rails'
# Use ActiveModel has_secure_password

gem 'bcrypt'
# I18n Translates

gem 'rails-i18n'
# Use Unicorn as the app server
# gem 'unicorn'
# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
# Use Devise for user auth

gem 'devise'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem "better_errors"
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
  gem 'mysql2'
  gem 'letter_opener_web', '~> 1.2.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'capistrano'
  gem 'capistrano3-puma'
  gem 'capistrano-rails', require: false
  gem 'capistrano-bundler', require: false
  gem 'capistrano-rvm'
  gem 'capistrano-ext'
  gem 'capistrano-rails-console'
end

group :production do
  gem 'figaro'
  gem 'puma'
  gem 'mysql2'
  gem 'rails_12factor'
  gem 'redis', '~> 3.0'
end

gem 'devise-encryptable'
gem 'fog'

**Comment by Rodrigora** [comment]
Hi @goalkeeper112 

Yes, this gem is using rails 4.2 as a dependency. We'll need to upgrade this to Rails 5

I'm out of time to check this right now; maybe I'll have time later this week.

**Comment by goalkeeper112** [comment]
Nice bro

**Comment by Rodrigora** [comment]
Hey, version 0.0.2 is working with Rails 5
